- inrix/python/inrix_utils/aggregate.py
- inrix/python/inrix_utils/create_index.py
- inrix/python/inrix_utils/finish_partition.py
- inrix/python/inrix_utils/move_data.py
- inrix/python/inrix_utils/utils.py
https://softwareengineering.stackexchange.com/questions/334518/how-to-dry-with-calls-to-a-database-to-execute/334569#334569
Fixes #10
> Created and tested the retry function

- bluetooth/readersdown/brokenreaders.py
Ensure that if no routes reported yesterday, email says something failed.
> Close #120

- here/README.md
- here/gis/README.md
- here/traffic/README.md
- Adds information on what traffic patterns are and how to bring them into the database
- Adds documentation on how to prepare traffic data for routing.
- #205 
- #187 
- Legibility but I'm going to merge anyway so links aren't broken
> Here routing docs

- bluetooth/api/README.md
- Adds installation instructions for time parsing.
- 
- #
- Nothing
> Add installation instruction for package time_parsing

- dags/pull_here.py
- here/traffic/here_api.py
- here/traffic/sql/trigger_ta.sql
- Adds the correction factor to the here traffic analytics trigger 
- Updates the here_api python file to specify the columns being copied
- #257 
- Also resolves #253
- Does this actually work?
> Here correction factor

- dags/pull_interventions_dag.py
- gis/gccview/pull_interventions.py
- Automate pulling in interventions 
- #301
- dag file
> Intervention dag

- dags/pull_here.py
- dags/pull_miovision.py
- To match the dags files as the ones on Airflow currently
- Fix schedule interval 
- Remove refresh view for pull_miovision
- Update dag for pull_here
> Fix dag schedule_interval

- gis/gccview/pull_interventions.py
- Allow features with no geometry to be inserted
- #301
> Allow null geometry to pass through

- volumes/miovision/api/intersection_tmc.py
- Enables Miovision API script to retry pulls after experiencing an HTTP 500 error.
- Revise error handling class structure and logic to simplify the `pull_data` function.
- #335
- High-level scan of the script changes to make sure there aren't any egregious errors.
- Smoke testing has been done by running `python intersection_tmc.py run-api --path /etc/airflow/data_scripts/volumes/miovision/api/config.cfg --start_date 2019-07-01 --end_date 2019-07-02 --pull` and checking the log output.
> Revise error handling structure in Miovision API script

- dags/readme.md
- Creates a README for the `dags` folder 
- Describes how to deploy airflow scripts
- #322
- What's missing?
> Airflow documentation

- dags/pull_wys.py
- wys/api/python/wys_api.py
- Uses execution date (ds)
- 
- #361 
- See how I fix it?
> Modernize WYS Airflow

- dags/readme.md
- Add steps to update existing airflow dag to readme in /dag
- 
- #
- steps
> Add steps to update an existing airflow dag

- dags/readme.md
- add steps to create a new dag
- # nan
- steps
> Add steps to create a new dag

- volumes/miovision/sql/function-determine_working_machine.sql
- Small change to speed up island-finding CTE in Miovision's `determine_working_machine`.
- Formatting changes for clarity.
- Scan of the code changes to make sure nothing obvious is broken.
- I'll need someone to switch the owner of `determine_working_machine` to me so I can replace it.
> Speed-up determine_working_machine

- dags/vz_google_sheets.py
- removes unnecessary indents in script
- #294
- nothing to review, just the extra indent space in the tasks have been removed
> ssz2021 dag: fix indents

- volumes/miovision/README.md
- Fixes link bug in Miovision Readme
- Adds a note about deleting and re-pulling data
- None
- Review changes to Readme
> Fix Miovision Readme

- volumes/README.md
- volumes/sql/artery_locations_px.sql
- volumes/sql/artery_traffic_signals.sql
- Creation of two useful view and an update to the README
- #447 
- sql and readme
> Artery Code useful views

- wys/api/python/wys_api.py
- Fixes [wys_api.py](https://github.com/CityofToronto/bdit_data-sources/blob/e2fc0083d6cbad678c7a81f43acf02a2606cf6bb/wys/api/python/wys_api.py) to handle all 1-hour intervals
- Correct a misplaced parenthesis
- #455 
- [wys_api.py](https://github.com/CityofToronto/bdit_data-sources/blob/e2fc0083d6cbad678c7a81f43acf02a2606cf6bb/wys/api/python/wys_api.py)
> handling skipped intervals in wys_api #455

- wys/api/python/wys_api.py
- fixes an error in the code merged at #456 
- converted a tuple into a list to be able to update it
- #455
> Wys daily updates

- wys/api/python/wys_api.py
- Bugfixes 
- 
- Closes #455 
- Dunno, I tested this so I'm going to merge it into master 😏
> Bugfixes to WYS daily pipeline 

- dags/pull_here.py
- Add `retry` to pull_here DAG
- #465
- the two lines I changed in the DAG
- If a 45 min interval + 3 times retry is good
> #465 Add retry to pull here DAG

- dags/pull_here.py
- Fix retry in pull here dag
- #465
- That retry = 0 is no longer in the task :meow_dundundun:
> Fix retry in pull here dag

- bluetooth/api/blip_api.py
- bluetooth/api/requirements.txt
- Remove the usage of pygresql package and use psycopg2 instead
- #131
- If it works
- I feel like there was something about the upsert that I had problem with, so the upsert statement
- Now that I think about it more, I think there was a problem with upsert that I haven't fixed yet
> smol pr for changing pygresql to use psycopg2 in blip api fr this time

- dags/readme.md
- updates the readme.md on the dag landing page
- #477
- is the command to pull from master correct?
> #477 dag documentation updated

- .gitignore
- parking/tickets/create-table-tickets_raw.sql
- parking/tickets/import_tickets_data.R
This pull request contains two files to be used to process and store parking ticket data from the City of Toronto's Open Data Portal, located here: 
https://open.toronto.ca/dataset/parking-tickets/
None.
General adherence to standards for data source ingestion
> Script for storing raw parking ticket data from Open Data

- dags/readme.md
I was pulling from master and I got a fatal error so I had to make a safe.directory and now that's in the readme yay!
- adds instructions to the dag readme for when git needs you to tell it you're safe
- 
- none created
- step 11 of creating a new dag (that's the only place I made changes and it's pretty short)
> added 'fatal error' response

- here/traffic/here_api.py
- so the script runs again
- closes #500 
- the two changed lines
> #500 Add in return access token and catch error in here api

- here/here_aggregation.md
- formats code blocks in docs for legibility / consistency
- code blocks were hard to read
- check that I didn't change the actual code (except I added an `AND` where it seemed necessary)
> Make formatting (tabs v spaces mostly) consistent for HERE aggregation docs

- dags/assets_pull.py
- Created Slack notification for future errors
- Fixed the Issue of column name mismatch
- #517 
- Slack alert code
- Updated col_names and att_names for RLC
> Traffic sig silent failures fix

- volumes/miovision/sql/create-table-classifications.sql
- creates a primary key on the table
- lets other tables reference this key
- check syntax
> Set primary key on classifications table

- volumes/miovision/sql/function_create_volume_table.sql
> #439 miovision bot permission fix: eoy maintenance 

- dags/log_cleanup.py
- add log cleanup dag to master
- There was no issue 
- there is actually no slack alerts for this dag, should we add it? @radumas
> Add log cleanup dag

- dags/assets_pull.py
- dags/check_miovision.py
- dags/check_rescu.py
- dags/collisions_replicator_transfer.py
- dags/eoy_create_tables.py
- dags/pull_here.py
- dags/traffic_transfer.py
- Update DAGs used in data script (not dev_script) to be compatible with airflow 2, mainly changing postgreshook, postgres opeartor and slackwebhookoperator
- Closes #524 
- no typos in the new ones?
> Update DAGs in data script to be as cool as airflow 2

- dags/log_cleanup.py
- Change path from `core` to `logging` since the new config file moved base_log_folder from core to logging in the new airflow version
- unbreak broken dag
- #529
- tested on dev_script, it works 👍🏼
> #529 update core to logging

- dags/vz_google_sheets.py
- gis/school_safety_zones/schools.py
- Updated the path to `schools.py` script that is imported from `vz_google_sheets` DAG
- now the path is independent of the repo path 
- Marking any year with invalid records as `failed`
- while continuing inserting all other valid records
- resolves #511 
- resolves #512
> School safety zones

- CyclingApp/README.md
- updates/ removes broken links
- adds references to external research contextualizing the dataset
- NA
- `CyclingApp/README.md`
> Partial update to cycling app docs

- here/here_aggregation.md
- Updates example SQL code to reflect current Data & Analytics code standards for SQL (per SQLFluff)
- removes some unnecessary/default typecasting, to reduce verbosity of examples
- `here/here_aggregation.md` code examples
> Update sample SQL per code standards

- gis/school_safety_zones/schools.py
- Removes white spaces from raw dates
- #555 
- Function `enforce_date_format` in `schools.py`
> Remove white spaces from SSZ dates #555

- here/here_aggregation.md
- fixes a few typos and formatting issues
- tries to clarify a few minor things
- NA
- not much
> Some light formatting and typo-fixing

- parking/readme.md
- mainly just identifies the source of this data
- #35 
- facts
> Add simple `parking/` readme

- README.md
Forgot to save changes :facepalm:
Real amateur hour here.
> Open Data is back.

- here/README.md
- here/traffic/sql/create_here_valid_range.sql
- create a valid range table in schema here
- update readme to point to that table
- closes #554 
- the readme 
- and the sql
> Here valid range

- README.md
- formats directory links consistently below subheadings
> Format directory links consistently

- dags/gcc_layers_pull.py
- gis/gccview/README.md
- gis/gccview/gcc_puller_functions.py
- Replaces outdated bikeways layer with new "Cycling Infrastructure" layer from GCC. 
- #608 
- @tahaislam please test in on-prem env. 
Please backfill gcc puller task: `bigdata_task_cycling_infrastructure`
> Update bikeways -> cycling_infrastrucutre

- dags/check_miovision.py
- dags/check_rescu.py
- dags/collisions_replicator_transfer.py
- dags/eoy_create_tables.py
- dags/gcc_layers_pull.py
- dags/log_cleanup.py
- dags/pull_here.py
- dags/pull_miovision.py
- dags/pull_wys.py
- dags/refresh_wys_monthly.py
- dags/traffic_signals.py
- dags/traffic_transfer.py
- dags/vz_google_sheets.py
- Convert DAG owners list into comma separated string
- #595 
- All DAGs in the `dags` folder
- Merge into `master` and pull into `data_scripts`
> Convert DAG owners list into comma separated string

- README.md
- mentions the short-term count program on the main readme
- This is a core dataset and its absence was conspicuous
- links work
- facts
nada
> Mention short-term count program in main readme

- volumes/miovision/README.md
- updates an old field name that sneaked through review of #589 and made it into the docs
> Update anomalous field name in docs

- wys/api/README.md
- Update the documentation of the `wys_api.py` script to match the updated code
- #400
> Updating WYS (wys_api.py) doc

- volumes/miovision/README.md
- it's in the title
- response to https://github.com/CityofToronto/bdit_data-sources/issues/634#issuecomment-1587977748
- spelling?
- NA
> Note when `classification_uid` 10 began

- volumes/ecocounter/.gitignore
- volumes/ecocounter/counts.sql
- volumes/ecocounter/data/pull-all-from-api.py
- downloads ecocounter data from their API
- API should be easier/better to use long term than excel exports
- nothing
NA
> Download ecocounter data from API

- dags/pull_weather.py
- Change the time of when pull_weather is set to run
- #
- the time (?
git pull in /etc/airflow/data_scripts
> Update pull weather start time

- dags/pull_wys.py
- dags/vz_google_sheets.py
- gis/school_safety_zones/schools.py
- wys/api/python/wys_google_sheet.py
- Updates `pull_wys` DAG and the helper script `wys/api/python/wys_google_sheet.py`
- Updates `vz_google_sheets` DAG and the helper script `gis/school_safety_zones/schools.py`
- resolves #683 
- The two updated DAGs and how they handle the timeout error of Google sheets connection
Merge into `master` and update `data_scripts`
> Handling Errors in WYS and VZ DAGs

- dags/collisions_replicator_transfer.py
- Fix the collision DAG name
- Delete unused imports in the DAG file
- #596 
- The collision DAG file
- Update `data_scripts`
> Fix Collision DAG Name

- dags/pull_here.py
- change bath operator path and add slack alert function
- #
- 
change symlink to use data_script
> Dag here data home

- dags/vz_google_sheets.py
- Added 2023 school safety zones (a new Google sheet and task)
- minor modification to reduce code redundancy
- #710 
- The `vz_google_sheets` DAG
- Deploy into `data_scripts`
> Adding 2023 School Safety Zones

- README.md
- volumes/README.md
- volumes/rescu/README.md
- volumes/vds/readme.md
- Consolidates some information from rescu readme to vds readme
- Updates volumes overview readme to reflect vds schema
- Notes rescu readme as deprecated
- Closes #708
> I0708 rescuvds readme cleanup

- here/README.md
- updates dead links
- dead links were dead
the urls
NA
> Update broken HERE doc links

- README.md
- adds a link to the readme (it was missing)
- fixes a typo
NA
NA
NA
> Fix typo, add link to readme

- dags/vds_pull_vdsvehicledata.py
- add a comma to fix a dag import error 
- #772
> #772 add a comma to vds_pull_vdsvehicledata

- here/traffic/here_api.py
- here/traffic/here_api_path.py
- remove unused mapversion param
- #
- 
git pull in airflow
> remove all mapversion from here api scripts

- volumes/miovision/api/intersection_tmc.py
A very small PR which adds some checks to Miovision `intersections_tmc.py` to check and exit if:
- no intersections found
- no intersections active between start and end times specified
- Closes #741 
Nothing
> #741 add checks if intersections active

- dags/pull_miovision.py
- dags/pull_wys.py
- Updates ordering of create partition tasks
- #811 
- We should merge these changes into #738 because pull_wys and pull_miovision are running off of that branch right now for testing.
> #811 make sure monthly partitions created after yearly

- dags/vds_pull_vdsdata.py
- removed outdated parameters in `create_partitions` task sql functions 
- #814
> 814 vds pull vdsdata incorrect sql parameters

- volumes/ecocounter/tables/flows.sql
- volumes/ecocounter/tables/sites.sql
- brings these SQL table definitions up to date with some changes in the database
- they were outdated
- nothing. Just needs a review to get merged. 
- Nada
> Update Ecocounter table definitions to match current schema

- volumes/miovision/update_intersections/Readme.md
- very small documentation update to codify intention to not include bike exits in aggregate tables. 
- #880 
-
-
> #880 update sql used to add to intersection_movements

- dags/gcc_layers_pull.py
- Uncomment updating the intersection table in the GCC Puller DAG
- Closes #807 
- One line was uncommented
- Deploy on Morbius
> Uncomment updating the intersection table in the GCC Puller DAG

- dags/dag_functions.py
- dags/gcc_layers_pull.py
- gis/gccview/gcc_puller_functions.py
- Add OTHER in query parameter for centreline puller
- Fix one missing package bug in dags_function (missing json)
- #837 
- the few lines of changed code.
Check symlink to data_scripts in morbius.
> Add centreline OTHER and fix a bug for gcc puller

- weather/README.md
- makes some minor fixes and clarifications to the readme for weather data
- typos, changed table name, etc
- grammar?
* nothing
> Misc. minor fixes and updates to `weather` readme

- gis/gccview/gcc_puller_functions.py
- Make date in comment less confusing
- 
- #962 
- 
git pull in morbius
> change gcc puller dag table commentdate format into yyyy-mm-dd

- volumes/miovision/sql/readme.md
- volumes/miovision/sql/table/create-table-volumes_15min.sql
- volumes/miovision/sql/table/create-table-volumes_15min_mvt.sql
- volumes/miovision/sql/views/create-view-volumes_15min_filtered.sql
- volumes/miovision/sql/views/create-view-volumes_15min_mvt_filtered.sql
- adds views which filter out anomalous ranges from volumes_15min and volumes_15min_mvt aggregate tables. 
- new comments on 15min tables directing to new views.
- #971
- table comments
- create views
> 971 miovision 15 minute views that filter out anomalous ranges

- volumes/short_term_counting_program/move_match/readme.md
- volumes/short_term_counting_program/move_match/speedvol_stats.sql
- volumes/short_term_counting_program/move_match/tmc_stats.sql
- Closes #810
- Provides sqls for calculating peak hour tmc and speedvol counts, plus speedvol mean speed, daily counts as well as 15th, 50th, 85th and 95th percentile speeds
- #810 
- This code was reviewed as part of a request and was lightly edited to remove the request-specific parts.
- Nothing - at this point we are saving it here for reference
> I810 move match

- volumes/ecocounter/views/create-view-counts.sql
- fixes some bugs in the `ecocounter.counts` view definition
- query didn't run / didn't match actual view in the DB
- stuff
- nothing
> Corrected bugs in `ecocounter.counts` view definition

- dags/ecocounter_check.py
- Closes #990 
- [It worked!](https://bditto.slack.com/archives/C04BWRWVB3L/p1719237903008049)
- #
- 
> #990 update schedule + execution_delta

- .github/workflows/codeql.yml
- Update codeql and checkout actions to latest major versions 
- Closes #1010 
- 
Nothing
> #1010 Update codeql and checkout actions to latest major versions

- volumes/miovision/getting_started.md
- volumes/miovision/sql/readme.md
- Update the `getting_started` readme to mention the filtered views front and centre. 
- Note the filtered views were already added to the main readme in another PR: https://github.com/CityofToronto/bdit_data-sources/pull/972
- Closes #982 
- 
> 982 updates to miovision getting startedmd

- volumes/miovision/getting_started.md
- update sql that filters for count approaches only
- #
- that one line chnage
nothin
> Fix miovision example sql

- dags/readme.md
A minor shuffling of dags docs as requested by @chmnata!
- Add description of files/folders in dags/ (including the functions in common_tasks, dag_functions)
- Add TOC
- Replace etc/airflow with data/airflow
- Reduce some duplication between "add a new DAG" and "update an existing DAG" sections
- #945 
- File structure
> #945 update dags folder readme.md

- volumes/miovision/sql/readme.md
- A small note in the readme about monitoring TTC intrusions using "entrance" movement_uid.  
- #960
- 
> #960 note for movement_uid = 7 about ttc row monitoring

- dags/gcc_layers_pull.py
- gis/gccview/gcc_puller_functions.py
- add `pavement_asset` layer to gcc_puller
- backfilled most recent dag run using `airflow dags backfill -t bigdata_task_pavement_asset -s 2024-04-01 -e 2024-07-01 pull_gcc_layers` ✅ 
- #620 
- 
> #620 add pavement_asset layer

- volumes/miovision/sql/views/create-view-open_issues.sql
- Update Miovision `open_issues` view. Join alerts with an overlap to the anomalous range, rather than only alerts fully contained within the AR. 
- #1047 
- 
- Nothing, already updated view.
> #1047 update alerts CTE

- volumes/vds/sql/insert/insert_raw_vdsdata.sql
- volumes/vds/sql/tables/create-table-last_active.sql
- Replace insert with upsert to ensure new sensors get added.
- #1057 
- Nothing, tested and working ✅
> 1057 bug vdslast active does not get updated with new sensors

- dags/pull_here.py
- dags/wys_check.py
- dags/wys_pull.py
- reschedule 3 afternoon dags to 5/6pm to give longer afternoon update window
- #1056 
-
> #1056 reschedule 3 afternoon dags to evening

- volumes/short_term_counting_program/README.md
- adds to documentation on pedestrian counting practices
- the documentation was lacking in this area
- words
- nothing
> Documunt short-term TMC pedestrian counts

- dags/bluetooth_check_readers_temp.py
- added dag to version control :octocat: 
- brought the DAG up to current standards with taskflow, common dag functions/slack alerts
- #1086 
- 
> 1086 temp bluetooth check readers dag failing silently

- volumes/miovision/api/intersection_tmc.py
- DST bug
- #1093
Tested with both DST and non-DST day; worked. 
Nothing.
> #1093 Fix miovision datetime bug

- dags/wys_pull.py
- wys/api/python/wys_google_sheet.py
Fix some small bugs in WYS google sheet pipeline.
- the xcom_pull values were missing task group name.
- there was an indentation error preventing all rows from being read (line 110 in original)
- #1130
- 
- Update data_scripts
> 1130 WYS read_google_sheets bug fixes: indent error, xcom not specified properly

- dags/pull_here_path.py
- here/traffic/here_api.py
- updates pull_here_path schedule
- allows extra token refreshes due to long query times recently
- #1186 
- 
Update data_scripts (I checked out the DAG from this branch)
> #1186 Update pull_here_path schedule

- dags/gcc_layers_pull.py
- gis/gccview/gcc_puller_functions.py
- Checks row counts of tables copied by gcc_puller:
- test:
- #1174
- 
> 1160 basic data quality checks gis

- dags/gcc_layers_pull.py
> #1199 fix bug in gcc_layers_pull from testing

- gis/centreline/readme.md
- add a line so markdown table works
- #
- 
> fix readme table structure

- dags/rodars_pull.py
- dags/vds_pull_vdsdata.py
- dags/vds_pull_vdsvehicledata.py
- extend retry time
- 
- #1198 
- 
Pull changes on Morbius, pull changes into other Rodars feature branch where DAG is currently running
> 1198 extend retry time on ITSC dags

- dags/dag_functions.py
> #1203 remove temp port 8080 redirect

- dags/ecocounter_open_data.py
- (due to addition of worktrees)
- 
- #
- 
> #1207 update Ecocounter readme path

- gis/centreline/readme.md
Based on simple exploration of the data
- better documents what this table contains
- statements were not accurate
- truth of statements
- nothing
> Slightly expand documentation of `gis_core.centreline(_latest)`

- dags/miovision_pull.py
- volumes/miovision/api/intersection_tmc.py
- Miovision support suggested end times are exclusive (even though our past year of experience suggests they are not). 
- #1242
- 
> 1242 miovision pipeline failing with duplicates detected error
