CityofToronto/bdit_data-sources

- dags/pull_miovision.py
- Add a step in the `pull_miovision` dag to refresh three materialized view after pulling data from the api
- dag script
> add refresh view in pull miovision dag

- volumes/miovision/sql/function-aggregate-volumes_15min_tmc.sql
- Fixes a bug in the Miovision data processing pipeline where the 15-minute aggregation script would pad out 1 hour 15 minutes around short gaps rather than 1 hour.
- #338
- Cursory glance at the code.
> Fix Miovision aggregation to properly use 1 hour pads for short gaps

- volumes/miovision/api/intersection_tmc.py
- Stop the API from pulling one extra bin of data beyond the endpoint of the datetime range (cherry-picked from [d9c042](https://github.com/CityofToronto/bdit_data-sources/commit/d9c042b18acf4ee52660aab2a69c03b7a05caa0a)).
- Fix a timestamp display issue in the logging.
- Closes #339 
- Closes #345
- Glance at the source code (and then push to productionization for tomorrow's run).
> Fix Miovision API Puller Bugs

- volumes/miovision/api/intersection_tmc.py
- Fixes a bug in `daterange` in `intersection_tmc.py` where the last interval of the range would be missing when `dt` divides evenly into `end_time - start_time`.
- Closes #355
- Confirm the fix and work in #355 is sensible.
- Quick brainstorm of edge cases where `daterange` may break that we should address.
> Fix missing timebin issue with daterange (#355).

- volumes/miovision/sql/csv_data/function-aggregate-volumes_15min_tmc_2020.sql
- volumes/miovision/sql/csv_data/function-find_gaps_2020.sql
- volumes/miovision/sql/function-aggregate-volumes_15min_tmc.sql
- volumes/miovision/sql/function-find_gaps.sql
- Synchronizes Postgres functions for Miovision API and CSV pipelines. In particular
- Makes variable names more clear in API gap-finding function.
- Ports the zero-padding CTE from `function-aggregate-volumes_15min_tmc_2020.sql` (CSV version) to `function-aggregate-volumes_15min_tmc.sql` (API).
- Closes #379.
- Scan of the changes to make sure I haven't introduced silly errors.
> Synchronize functions between Miovision CSV and API pipelines

- volumes/miovision/sql/csv_data/create-view-report_volumes_15min.sql
- volumes/miovision/sql/csv_data/function-aggregate-volumes_15min_tmc_2020.sql
- volumes/miovision/sql/function-aggregate-volumes_15min_tmc.sql
- volumes/miovision/sql/function-api_log.sql
- Removes Rick, Joven and myself from `miovision_api`/`miovision_csv` table ownership. 😩
- 😩
- Need admin help to switch ownership of all elements of `miovision_api` and `miovision_csv` schemas to `miovision_admins`.
- Charles to put #380 into production once that's finished (currently Joven owns a table that need to be changed).
- We should consider making it a rule that any permanent table generated outside of one's personal schema must be owned by an admin group. (I suppose that means I'll need to create `collisions_admins` and `vz_admins` groups. For the next purge we should change all schema element ownership in `vz_analysis`, `vz_challenge`, `vz_safety_programs`, etc. to group ownership.
> Remove former team membership from ownership

- wys/api/python/wys_api.py
- checks for null speed and count and only converts to `int` for non-NULL values in `parse_counts_for_location()` that takes in raw data records from the WYS api
- #388 
- pls review the fix
> catches null speed and count values #388

- collisions/GettingStarted.md
- collisions/Readme.md
- collisions/collisions_acc.sql
- collisions/collisions_alldata.sql
- collisions/collisions_collision_no.sql
- collisions/collisions_events.sql
- collisions/collisions_involved.sql
- collisions/pull_acc_script.py
- Adds table and view definitions for collisions dataset on Postgres.
- Adds a Python script, `pull_acc_script.py`, that manually retrieves `ACC.dat` from the MOVE server and uploads it to Postgres. This will become deprecated once the RDS gets moved to Canada East, but most of the Postgres components of the script should still be useful.
- Cleaned RDS of old versions of ACC, and added legacy suffixes to those tables that still have parent views in production (see #347 for progress).
- #348
- Check of the SQL scripts to make sure I'm not doing anything silly.
- Check resulting table structures on Postgres (under `collisions` schema) to ensure everything makes sense.
- Quick read of Readme.md to make sure I'm not missing anything.
- Should we get rid of `collision_factors.collision_id` and …
> Add first draft of collisions pipeline (#348).

- bluetooth/api/README.md
- bluetooth/api/blip_space_log.py
- create a process for checking the status of the blip server disks via REST API and log it
- implement a rotating file handler log so the `blip_space_log.log` always contains only one line, unless there's an error.
- #428 
- Check out the rotating file handler!
- Also the README.
> Log Blip Server Space Fixes #428

- dags/traffic_transfer.py
- volumes/README.md
- volumes/sql/traffic_new/func_upd_arc_link.sql
- volumes/sql/traffic_new/func_upd_arterydata.sql
- volumes/sql/traffic_new/func_upd_category.sql
- volumes/sql/traffic_new/func_upd_cnt_det.sql
- volumes/sql/traffic_new/func_upd_cnt_spd.sql
- volumes/sql/traffic_new/func_upd_countinfo.sql
- volumes/sql/traffic_new/func_upd_countinfomics.sql
- volumes/sql/traffic_new/func_upd_det.sql
- volumes/sql/traffic_new/func_upd_node.sql
- volumes/sql/traffic_new/logged_actions.sql
- volumes/sql/traffic_new/trfunc_log.sql
- volumes/sql/traffic_new/trfunc_traffic_if_mod.sql
- upserts data in 9 tables on traffic using data updated on TRAFFIC_NEW
- logs changes to 6 of the tables (3 tables were excluded from auditing because they are large and frequently updated).
- #462
- tested on airflow; it worked
- compared table record counts in both schemas and they matched
- reasonable output in logged_actions table
- maybe make sure the dag is efficient??? Would it be better to update all of the tables at the same time?
> Volume pipeline

- here/here_aggregation.md
- Updates and clarifies the current method of aggregating travel times with HERE data using the congestion network
- Moves table of contents off the top level, un-indenting all other headings by one step
- NA
- That this update makes the docs easier to read and more correct than currently
> Update to Congestion Network aggregation methods

- bluetooth/api/blip_api.py
- Got rid of _value_ attribute in json for outcome and routepoint column in `bluetooth.all_analyses`
- e.g. 
```
SELECT      all_analyses.analysis_id,
(all_analyses.route_points -> 0) ->> 'id'::text AS start_route_point_id,
(all_analyses.route_points -> 0) ->> 'name'::text AS start_detector,
(all_analyses.route_points -> 1) ->> 'id'::text AS end_route_point_id,
(all_analyses.route_points -> 1) ->> 'name'::text AS end_detector
FROM       bluetooth.all_analyses 
```         
returns the below correctly
analysis_id | start_route_point_id | start_detector | end_route_point_id | end_detector
-- | -- | -- | -- | --
1387957 | 116755 | C | 116754 | B
- #131
> Get rid of _value_ attribute for outcome_arr and routepoint_arr

- wys/api/README.md
- wys/readme.md
- moves WYS overview doc up a level, pulling text from the `api/` directory
- (partially duplicates some work in #557)
- `wys/` had no readme :'-(
- not much
> Move WYS overview README text up a level

- dags/gcc_layers_pull.py
- Updated the DAG to include specific tasks based on the environment variable `DEPLOYMENT`, which should be set in `/etc/systemd/system/airflow-webserver.service` and `/etc/systemd/system/airflow-scheduler.service` as follows:
```
[Service]
Environment="DEPLOYMENT=DEV" # PROD for prod servers
```
- #572 
- The `pull_gcc_layers` DAG file: `gcc_layers_pull.py`
> Run bigdata GCC puller tasks on the dev server only

- dags/assets_pull.py
- The format of the red light cameras' geometry has changed. This PR updates the [`traffic_signals_dag`](https://10.160.2.198/airflow/tree?dag_id=traffic_signals_dag) to handle these changes
- Resolves #599 
- The DAG file at `dags/assets_pull.py` (more specifically `pull_rlc` function/task)
- Update the main branch at `data_scripts` and update the DAG's link to point to the one in `data_scripts`
> Handle the new format of the RLC geometry

- dags/refresh_wys_monthly.py
- wys/api/sql/create-view-mobile_api_id.sql
- wys/api/sql/mat-view-stationary-signs.sql
- wys/api/sql/open_data/mat-view-stationary-locations.sql
- wys/readme.md
- Filters out signs outside of Toronto. 20m buffer applied to Toronto boundary to include signs on border (in particular 1 sign on Steeles). 
- formatting changes. 
- #530 
bdit_data-sources/wys/api/sql/mat-view-stationary-signs.sql 
contains the edits to filter out signs outside of Toronto. 
Run these scripts in RDS:
bdit_data-sources/wys/api/sql/create-view-mobile_api_id.sql
bdit_data-sources/wys/api/sql/mat-view-stationary-signs.sql
bdit_data-sources/wys/api/sql/open_data/mat-view-stationary-locations.sql
> I530 wys signs outside to

- volumes/miovision/README.md
- reclassifies streetcars as "buses"
- adds link to Miovision's documentation of this
- applies more standard formatting to that markdown table for readability
- That streetcars are in fact classified as buses
> Correct docs regarding miovision streetcar classification

- bluetooth/api/blip_api.py
- Fix blip api script bug so we can pull individual analysis_id using `-a`
- #641 
- that one line
Nothing
> #641 Blip_api: add tabbing and change to fetchall

- dags/pull_wys.py
- dags/vz_google_sheets.py
- Update two DAGs to use the new name of the function `_get_credentials()` of `GoogleCloudBaseHook` to match its name in Airflow 2.7.0
- resolves #681 
- Two DAGs: `dags/pull_wys.py` and `dags/vz_google_sheets.py`
- After merging into `master`, update the repo at `data_scripts`
> Quick Fix for Airflow Google Cloud Hook Credentials

- dags/assets_pull.py
- dags/check_miovision.py
- dags/check_rescu.py
- dags/collisions_replicator_transfer.py
- dags/eoy_create_tables.py
- dags/gcc_layers_pull.py
- dags/log_cleanup.py
- dags/pull_here.py
- dags/pull_interventions_dag.py
- dags/pull_miovision.py
- dags/pull_weather.py
- dags/pull_wys.py
- dags/refresh_wys_monthly.py
- dags/traffic_transfer.py
- dags/vz_google_sheets.py
- This PR makes our DAGs time-zone aware by explicitly specifying the time zone of each DAG's start_date
- resolves #685 
- In each DAG file (in `dags` folder), I imported `pendulum` and converted the DAG's `start_time` from `datetime` to `pendulum.datetime` with "America/Toronto" time zone.
- After merging the branch, we need to update `data_scripts` by running `git pull;`
> Make all DAGs time-zone aware

- dags/pull_wys.py
- wys/api/python/wys_api.py
- Separates `get_schedules` into a separate Airflow task to prevent failure from impacting rest of `pull_wys` task.
- Adds try except block to `get_schedules` to catch TypeError
- Change all tasks to taskflow api format
- Move connections out of top level to improve DAG parsing performance
- Closes #713 
- First time using TaskFlow API!
- See error in #713
- I haven't tested parsing the changes to the DAG
> I0713 wys get schedules failing with typeerror

- volumes/miovision/sql/create-mv-mio_cent.sql
- removes the `scannon` dependency from the `prj_volume.mio_cent` table (aka the table that conflates `centreline_ids` with Miovision intersection legs
- moves the table from `prj_volume` to `miovision_api`
- #699 
- Make sure the code runs; I tested it in my `scannon` schema but I don't have permissions for the `miovision_api` schema
- Someone who has create privileges on `miovision_api` should run the code
> #699 remove personal schema dependency on the miovision tcl conflation table

- dags/custom_operators.py
- dags/vds_pull_vdsdata.py
- dags/vds_pull_vdsvehicledata.py
- volumes/vds/sql/select/select-row_count_lookback.sql
- Adds a basic row count check to VDS DAGs, similar to existing `check_rescu`
- passing value for checks calculated based on average row count over lookback period. 
- Closes #702
- Is there a way to utilize `/vfh_data_mgmt/custom_operators/sql.py` without copying to bdit_data-souces? 
- Thoughts on sql with so many params (meant to be reusable)?
- Thoughts on reusing SQLCheckOperatorWithReturnValue for this? I also considered a modified SQLValue/SQLInterval CheckOperator but this was least effort.
- Update vds_* DAGs. 
- Gabe to update DAG section of VDS readme
> I0702 monitor vds count

- dags/dag_functions.py
- Choose the correct Slack channel for failure alerts based on the location of the running DAG. If a DAG is running from the path saved in the Airflow's variable `prod_env_path`, all its failure alerts will be directed to channel `data_pipelines` (also saved in Airflow as `slack_data_pipeline`). All other DAGs under development and running from other locations will send their failure alerts to channel `data_pipelines_dev` (also saved in Airflow as `slack_data_pipeline_dev`).
- You can still override the above rule by setting the argument `dev_mode` while calling the function `dags.dag_functions.task_fail_slack_alert`.
- The ultimate goal is to protect the main Slack channel used to receive failure alerts, `data_pipelines`, from getting flooded with alerts from DAGs under development or …
> Choose the failure alerts' slack channel based on the running DAG's location

- volumes/miovision/README.md
- volumes/miovision/update_intersections/Readme.md
Add a smol section to the miovision readme to reference the `centreline_miovision` table in the reference tables section
- adds a smol section about the centreline_miovision table to the Reference section of the miovision readme
- Closes #728
- Should I add anything to the `centreline_miovision` section?
Nothing!
> Update mio README.md

- volumes/vds/py/vds_functions.py
- While reviewing potential compatibility issues, I found and removed a no longer in use pd.read_sql helper function to clean up the codebase and prevent incorrect future use. 
- Closes #761
Nothing
Nothing
> #761 remove unused pd.read_sql function

- wys/api/sql/function-aggregate_speed_counts_one_hour_5kph.sql
- wys/api/sql/function-mobile-summary.sql
- wys/api/sql/function-stationary-sign-summary.sql
- Fixes a bug in the join conditions to `wys.speed_bins_old` in `wys.mobile_summary_for_month` function.
- Unifies the join conditions in all 3 instances where we join to this table
- sql fluff 
- #758
- 
```sql
TRUNCATE TABLE wys.mobile_summary;
WITH active_mobile_signs AS (
SELECT location_id, api_id, installation_date, removal_date
FROM wys.mobile_api_id
WHERE installation_date < '2023-11-01'::date
)
INSERT INTO wys.mobile_summary
(location_id, ward_no, location, from_street, to_street, direction, installation_date, removal_date, days_with_data, max_date, schedule, min_speed, pct_05, pct_10, pct_15, pct_20, pct_25, pct_30, pct_35, pct_40, pct_45, pct_50, pct_55, pct_60, pct_65, pct_70, pct_75, pct_80, pct_85, pct_90, pct_95, spd_00, spd_05, spd_10, spd_15, spd_20, spd_25, spd_30, …
```
> #758 consistent join conditions for speed_bins_old + fluff

- dags/pull_miovision.py
- dags/vds_pull_vdsdata.py
- dags/vds_pull_vdsvehicledata.py
- Small bug fix across 3 DAGs with new partitioning tasks: jinja templating doesn't work in params of PostgresOperator. 
- #788
- [Tested](https://trans-bdit.intra.prod-toronto.ca/airflow/dags/pull_miovision/grid?dag_run_id=scheduled__2023-12-01T08%3A00%3A00%2B00%3A00&task_id=check_partitions.create_month_partition&tab=logs) ~~We should test `pull_miovision` before merging (the other ones will only run on 2024/1/1).~~
> 788 `pull_miovision.check_partitions.create_month_partition` jinja templating bug

- dags/common_tasks.py
- dags/dag_functions.py
-  Copy comments on tables while copying the actual contents in replicator DAGs
- Specify which table failed to get copied in the Slack notification
- Closes #786 
- An added sql query to `copy_table`
- An extra option to send the extra failure message
- Deploy into data_scripts
> Copy tables comments in replicator DAGs

- dags/miovision_check.py
- dags/sql/create-function-summarize_gaps_data_check.sql
- removes `id_col_dtype` param from `public.summarize_gaps_data_check`. Replace with always passing `null::text` to `generic_find_gaps` when summarizing.  
- #833 
- Tested in gwolofs schema. Working! 
- DELETE FUNCTION public.summarize_gaps_data_check;
- replace with new function from: dags/sql/create-function-summarize_gaps_data_check.sql
- update `miovision_check` DAG
> 833 regtype bug in publicsummarize gaps data check

- volumes/miovision/README.md
- volumes/miovision/sql/table/create-table-volumes_15min.sql
- volumes/miovision/sql/table/create-table-volumes_15min_mvt.sql
- Adds missing uid defaults to `miovision_api.volumes_15min`  and `miovision_api.volumes_15min_mvt`
- Add to github definition missing index on `miovision_api.volumes_15min_mvt` column `processed`.
- #838 
Nothing - changes are to reflect what exists in bigdata.
> 838 missing uid defaults in miovision aggregate tables

- dags/miovision_check.py
- volumes/miovision/sql/data_checks/select-ongoing_intersection_outages.sql
- Revises distinct Miovision intersection data check to provide more detail (name, duration, last received), eg: 
```
{"Front / Spadina (uid: 6) - data last received: 2024-01-22 (1 day)",
"Front / Bay (uid: 7) - data last received: 2023-12-30 (24 days)", 
"Jane Street and Wilson Avenue (uid: 62) - data last received: 2023-12-28 (26 days)"
}
```
- #843
- Should we add adjust `min_duration` param to 1 day so we don't hear about outages until 2nd day?
> #843 revise data check to report ongoing outages

- volumes/miovision/api/intersection_tmc.py
Small bug fix to fix the broken import of fromisoformat. Tested with run-api and backfilling those dates was successful.
- #848
> update fromisoformat usage to: datetime.datetime.fromisoformat

- dags/miovision_pull.py
- volumes/miovision/api/intersection_tmc.py
- changed the cli params to: `pull` (flag to pull data) and `agg` (flag to aggregate data).
- this will help when adding new intersections (easily run all the clear/aggregate commands in one line, separate from pulling).
Tested this successfully for multiple dates/intersections: 
```
(airflow_venv) XXX@ip-XXX:~/bdit_data-sources/volumes/miovision/api$ python3 intersection_tmc.py run-api --path='/data/airflow/data_scripts/volumes/miovision/api/config.cfg' --agg --intersection=71 --intersection=72 --start_date=2024-01-01 --end_date=2024-01-10
01 Feb 2024 14:00:08            INFO    Skipping pulling volume data.
01 Feb 2024 14:00:08            INFO    Aggregating data from 2024-01-01 00:00:00 to 2024-01-10 00:00:00
01 Feb 2024 14:02:15            INFO    NOTICE:  Found a total of 934 gaps …
```
> 835 add agg param to miovision run api

- dags/miovision_pull.py
- dags/pull_wys.py
Fixes the trigger rules of `create_month_partition` task in `pull_wys` and `miovision_check` by changing to `none_failed_min_one_success`. 
- #856 
- We should test this change before merging.
> #856 change trigger rules of create_month_partition

- volumes/miovision/sql/function/function-aggregate-volumes_15min_mvt.sql
- Significant speed improvements for aggregate_15_min_mvt, especially for long time ranges.
- this aggregation (intersection 68 from 2023-01-23 to 2023-06-29) took 6 hours today. I had similarly bad performance last week for other new intersections over long time ranges. It takes about 15s with the new version of the function.  
> 07 Feb 2024 16:07:17            INFO    Updated gapsize table and found gaps exceeding allowable size
> 07 Feb 2024 22:34:48            INFO    Aggregated intersections [68] to 15 minute movement bins
> 
- #862 
- we should still test the performance of the full function with the update part.
- replace function in postgres
> #862 much faster version of aggregate_15_min_mvt

- volumes/miovision/sql/views/create-view-volumes_daily.sql
- Adds context from `anomalous_range` table to filtered `volumes_daily` (see sample in the comment below)
- new columns `anomalous_range_caveats` and `anomalous_range_uid` are arrays to support multiple issues per row (last row below)
- #867 
- What do you think of the formatting of the anomalous_ranges and the information contained in the extra columns? We can also consider using `string_agg` instead of `array_agg`. 
- You can see this in action at `gwolofs.volumes_daily`. Already confirmed that:
```sql
SELECT (SELECT COUNT(*) FROM gwolofs.volumes_daily) = (SELECT COUNT(*) FROM miovision_api.volumes_daily)
```
- DROP existing view and replace with new definition.
- After changes are approved I will update the readme.
> #867 add AR notes to volumes_daily

- dags/common_tasks.py
- Adds additional detail to replicated table comments to indicate source, time copied. 
- Tested! New comment on traffic.arteries_centreline is: 
>Contains a mapping of `centreline_id` to `arterycode`. This is used for mapping studies to the Centreline. Last updated on 2024-03-21.
Copied from "move_staging"."counts_arteries_centreline" by bigdata repliactor DAG at 2024-03-21 17:32.
- #906 
- Update DAG in data_scripts
> 906 add lineage to replicated table comments

- dags/common_tasks.py
- The new line character prevents the additional comment from being seen in the preview. Remove.
Before: 
After: 
- #906 
- Checkout common_tasks in data_scripts.
> #906 remove new line from comment

- dags/replicator_table_check.py
- Creates a new DAG (`replicator_table_check`) to monitor the MOVE -> bigdata replication process 
- This will help notify us if the list of tables being replicated is out of sync (hint: it currently is)
- See latest slack alerts for review:
https://bditto.slack.com/archives/C021YMH9BK5/p1713196079217679
https://bditto.slack.com/archives/C021YMH9BK5/p1713196079227109
- #927 
- 
- For @peter-lyons: we should have the MOVE replicator trigger this DAG through the API at the same time as the counts and collisions replicators.
> 927 add a replicator health check

- volumes/short_term_counting_program/sql/tmc_miovision_long_format.sql
- Adds the original column name and the original text classification from the short-term TMC data to the long-format table
- #918 
- Should we include more? I realize this is perhaps not the most efficient but don't want people to do text processing every time. We could have some lookup from this.
- 
I already created the new version 😼
> #918 Add text columns for movement & original classification

- volumes/ecocounter/readme.md
This cleans up some markdown tables in the EcoCounter docs to make them more legible. 
@gabrielwol I might gently suggest that whatever code generated these tables in the first place is perhaps worth reconsidering. It certainly doesn't work well for long descriptions, line breaks, null values, or geometry types.
> Clean up the Ecocounter docs

- gis/centreline/sql/create_matview_centreline_intersection_point_latest.sql
- gis/centreline/sql/create_matview_centreline_latest.sql
- gis/centreline/sql/create_matview_intersection_latest.sql
- adds a unique id field to the beginning of these 3 mat views so they can be added to qgis projects without error.
- #969
- 
- run these 3 sqls
> #969 add row number to gis_core latest mat views

- volumes/ecocounter/readme.md
- volumes/ecocounter/tables/sites_unfiltered.sql
- volumes/ecocounter/updates/ecocounter_centreline_updates.sql
- volumes/ecocounter/views/create-view-sites.sql.sql
- adds `centreline_id` to `ecocounter.sites` and `ecocounter.sites_unfiltered`. 
- a sql script used to identify new matches
- #966 
- Decision to add centreline_id to sites and not to flows. I figured for flows it would be duplicated between the flows at a given site which would make it very difficult to visualize. 
- Should I also add cl_geom to `ecocounter.sites` view?
Nothing.
> #966 add centreline_id to ecocounter.sites and sites_unfiltered

- volumes/vds/sql/insert/backfill_v15_from_cnt_det.sql
- prepare some RESCU data for analysis in a data request for MTO
- we have some older RESCU data in VDS schema now!
- some of this data is older than me!
- data from pre-2017 was infilled
- data from 2017-2021 (overlaps existing range) was inserted if it filled a missing day
- added some new rows to vdsconfig and entity_locations tables based on data in arterydata. 
- #964 
- I was pretty careful but a quick sense check would be helpful.
> 964 insert old rescu data from trafficcnt det into vds

- dags/ecocounter_check.py
- dags/miovision_check.py
- volumes/ecocounter/data_checks/select-ongoing_outages.sql
- volumes/ecocounter/data_checks/select-unvalidated_sites.sql
- volumes/miovision/sql/data_checks/select-ongoing_intersection_outages.sql
- changes two daily "_check" DAGs to weekly.
- adjust the schedule interval, external task sensors, and the sql params
- removed a non critical `check_gaps` check for miovision gaps > 4 hours, < 1 day
- #953 
- My method of linking weekly dag to daily: set task sensor to look 1 week ahead of schedule interval.
- nothing
> 953 reduce notification frequency to weekly

- dags/pull_here.py
- here/traffic/here_api.py
- Make pull here dag triggers dependent dag top down instead of down up using external task sensors. Dependent dags are stored in a variable for easy add/remove in the future. 
- #977 
Currently linked to my data home, removed all the other depedenent dag's external task sensor for testing and it worked today! FYI triggered dependent DAG runs are tagged as `manual run`. 
Will have to 
`ln -sf`
> #977 change here to use triggerdagoperator

- dags/ecocounter_pull.py
- volumes/ecocounter/pull_data_from_api.py
- captures 401 and other bad api status_codes (encountered during testing, but doesn't appear to be the issue)
- changes schedule to 10am to capture data from some late arriving sensors (this was the issue)
- add logging for when 0 volumes are pulled for a site
See runs from Master (Log 1) / 973 (Log 2) here: https://trans-bdit.intra.prod-toronto.ca/airflow/dags/ecocounter_pull/grid?dag_run_id=scheduled__2024-06-12T07%3A00%3A00%2B00%3A00&task_id=data_checks.check_volume&tab=logs
- 14K rows pulled at 3AM ❌ 
- 21K rows pulled at 9:40AM ✔️ 
- #973 
-
> 973 ecocounter investigate discrepency between bigdata and online dashboard tools

- volumes/vds/sql/views/create-view-detector_inventory.sql
- Add row_number (uid) to detector_inventory to make view mappable in QGIS
- 
- #985 
- 
> Add row_number to detector_inventory

- volumes/ecocounter/functions/function-fn_update_last_active.sql
- volumes/ecocounter/readme.md
- volumes/ecocounter/tables/counts_unfiltered.sql
- volumes/ecocounter/tables/flows_unfiltered.sql
- volumes/ecocounter/tables/sites_unfiltered.sql
- volumes/ecocounter/views/create-view-flows.sql
- volumes/ecocounter/views/create-view-sites.sql
- adds first_active and last_active columns to ecocounter sites, flows, sites_unfiltered, flows_unfiltered
- adds tigger on ecocounter.counts_unfiltered and a new function to update first_active and last_active columns on each update/insert. 
- Closes #987 
- First use of `TRIGGER... REFERENCING NEW TABLE` ! 
- volumes/ecocounter/functions/function-fn_update_last_active.sql
Nothing
> 987 ecocounter first active and last active columns

- dags/common_tasks.py
- dags/dag_functions.py
- dags/replicators.py
- Check for non-zero row count in source table before and destination table after truncate/insert.
- The dynamic task mapping is now done over task_group instead of task so that `check_source -> copy_table -> check_dest` happens in sequence for each map index (copy shouldn't proceed if source check failed)
- I tested successfully with a dummy table variable and then tested successfully with the actual table variables. I caught one empty table in move_staging which I notified MOVE about: `move_staging.collision_factors_cyccond` (failure msg [here](https://bditto.slack.com/archives/C04BWRWVB3L/p1719331402031249))
- Closes #645
- 
Update in data_scripts
> 645 replication processes check if data

- volumes/ecocounter/readme.md
- volumes/ecocounter/views/create-view-counts.sql
- removes anomalous ranges from the `ecocounter.counts` view  
(they are still in the unfiltered tables)
- closes #995 
- make sure the query is still nice and snappy
- replace existing view with new definition
> Filter anomalous ranges from Ecocounter `counts`

- dags/common_tasks.py
- There was a bug in `day_no` column of MOVE's `countinfo` and `countinfomics` and Maddy and Raph agreed it was best to remove that column from bigdata.
- In order to do this I had to alter the dependencies on those columns (use `date_part('isodow'...)` instead), drop the columns, and then change the replicator to pull column names from the destination table instead of the source table. 
- Now we are free to drop deprecated columns like this from the destination tables without breaking the replicator.
- Closes #952
- 
- update dag link back to data_scripts
> #952 replicate using destination columns instead of source columns

- volumes/vds/sql/views/create-view-detector_inventory.sql
- one line fix to detector_loc formula
- tested using:
```sql
SELECT upper(e.main_road_name::text) || COALESCE(' and '::text || upper(e.cross_road_name::text), ''::text)
FROM vds.entity_locations AS e
WHERE division_id = 2 AND e.cross_road_name IS NULL
```
- Closes #992
- 
> #992 fix vds detector_loc formula

- dags/pull_here.py
- Update execution date to logical date as execution is depreciated as of 2.9.1
- Switch from bash operator to task.bash, introduced in 2.9.1
- #980 
Worked for today!
git pull in data script and ln sf that
> #980 update logical date and switch to task bash

- volumes/miovision/sql/readme.md
- A small update to classifications readme to note why Bus is excluded from Vehicle class. 
- There is no evidence that Motorized Vehicles / Bus classifications overlap so no cautions needed there. 
- Nate already noted the date the classification changed under #671.
- Closes #634 
- 
> #634 Minor classifications readme.md update

- volumes/miovision/sql/data_checks/select-ongoing_intersection_outages.sql
- Chris prefers this id for entering into his tracker.
- #
- 
> Change intersection_uid to id in ongoing_outages select

- dags/gcc_layers_pull.py
- gis/gccview/gcc_puller_functions.py
- test/integration/test_dags.py
- move GCC layers and Primary key dictionaries to Airflow variables
- Dynamic DAG generation for bigdata/ptc GCC layers using Airflow variable which stores credentials, deployment
- added mat view refreshes to Airflow variable: easier addition of new aggregations!
- Closes #1032 
- I couldn't think of an obvious way to make mat view aggregations their own Airflow tasks in a dynamic way so I just added them to the pull_layers task. Thoughts?
- change data_scripts link in Morbius
> 1032 move gcc puller tables to airflow variable

- dags/tti_aggregate.py
- Retire citywide tti DAG
- Add a new DAG that process both citywide tti and downtown tti
- #1041 
- ln -sf 
Tested for today, successfully triggered by the pull_here DAG and successfully aggregated both citywide and downtown tti
> #1041 add new tti aggregation dag

- volumes/miovision/sql/data_checks/select-ongoing_intersection_outages.sql
- remove limited lookback window in miovision intersection outages check. Use `volumes_daily_unfiltered` instead to maintain speed. 
- Closes #1039
- 
- Pull into data_scripts
> #1039 remove limited lookback window in intersection outages check

- dags/assets_pull.py
- gis/assets/README.md
- gis/assets/sql/traffic_signals.sql
- do not add temp (portable) traffic signals to `vz_safety_programs_staging.signals_cart`
- add removed_date and temp_signal fields to `gis.traffic_signal`
- **Note:** modifications tested under `gis.traffic_signal_copy`
- Closes #1079
- It was mentioned we should only store this information only in one place; I elected to store it in a function in assets.py. 
- update DAG link
- `DROP TABLE gis.traffic_signal_copy`
- Add columns:
```sql
ALTER TABLE gis.traffic_signal ADD COLUMN removed_date date;
ALTER TABLE gis.traffic_signal ADD COLUMN temp_signal text;
```
> 1079 remove portable traffic signals from vzdashboard, add fields to `gis.traffic_signal`

- gis/school_safety_zones/README.md
- Updates README to better explain
- what permissions need to be granted on sheet?
- correct email / service account?
- Also reorganized the flow of the README to deemphasize local development
- Close #1066 
- Close #1067 
- Did I hit the right points
Documentation only
> #1067 #1066 Update instructions for adding a new spreadsheet

- constraints.txt
- requirements.in
- requirements.txt
- update airflow to 2.10.2
- add http, ftp providers to requirements.in (they were being installed via airflow_setup.sh)
- `pip install "apache-airflow[celery,postgres,google,slack,ftp,http]==${AIRFLOW_VERSION}"`
- #1082 
- 
> #1082 upgrade airflow to 2.10.2

- dags/gcc_layers_pull.py
- gis/gccview/gcc_puller_functions.py
- Now that Morbius Airflow is upgraded past 2.9.3 we can implement named mapped tasks (`map_index_template`)
- See successful test in `gcc_pull_layers_bigdata`. ✅ (tested without unnecessary update of GIS tables by commenting out parts of `pull_layer`). 
- Also fixed small bug from #1035 (`dag_name` -> `item`).
- #1043 
- 
Update DAG link in Morbius.
> #1043 add map_index_template, fix name->item bug from #1035

- gis/centreline/readme.md
- gis/centreline/sql/create_view_routing_centreline_directional.sql
The flow of traffic is opposite the drawn direction for one way streets that are -1
- Fix a bug routing on one-way streets
- #1091 
- Other examples worth testing? this isn't going to be perfect given the known issues with routing along the centreline
> Fix #1091 by properly filtering one-way streets

- volumes/ecocounter/functions/create-function-identify-outages.sql
- Repull days without all bins present
- Tested this on the last 60 days and 100% (108 days) of partial data were filled 🥳 Will proceed with backfilling all data.
- #1101
- 
> #1101 Repull days without all bins present

- bluetooth/sql/bt_eoy_create_tables.py
- dags/eoy_create_tables.py
- eoy_table_create DAG was targeting wrong year
- Add a task to calculate `yr` in a more pythonic way
- Made bluetooth task more consistent; receive year instead of ds
- Add here.ta_path yearly table task
- #1104 
- 
> 1104 `eoy_table_create` bug fixes

- dags/bluetooth_check_readers_temp.py
- Make silent alerts not silent 
- #1087 
- the switching to custom operator 
> #1086 switch alerts to use custom operator

- dags/pull_here.py
- dags/pull_here_path.py
- here/traffic/here_api.py
- here/traffic/here_api_path.py
- add retries for access_token while maintaining same request_id
- remove some duplicate function definitions (with some extra work pull_here and pull_here_path could be further deduped)
- Apply similar task.bash structure to pull_here_path that already existed in pull_here.  
- Closes #204, #1073 (duplicate issues)
- 
- Update data_scripts links
> 1073 here pull token expired error

- gis/centreline/sql/create_function_get_centreline_btwn_intersections.sql
- There was a mismatch between `cost_length` in the new view and `cost` in the function
- #1092 #1091 
- Is the documentation correct now?
Nothing, I did a live fix :meow_mage:
> Bugfix #1092 mismatch in cost vs cost_length

- nohup.out
- volumes/miovision/sql/function/function-aggregate_volumes_daily.sql
- volumes/miovision/sql/readme.md
- volumes/miovision/sql/table/create-table-intersection_movements.sql
- volumes/miovision/sql/views/create-view-monitor_intersection_movements.sql
- Make sure bikes in crosswalk and bike exits do not end up in aggregate tables (via intersection_movements)
- Delete existing bikes in crosswalk and bike exits. 
- #1065 
- @radumas  **Do we still want to do this, or change tack to follow MOVE which is now including bikes in crosswalk**
```sql
DELETE FROM miovision_api.volumes_15min_mvt WHERE classification_uid = 7;
DELETE FROM miovision_api.volumes_15min WHERE classification_uid = 7;
DELETE FROM miovision_api.intersection_movements WHERE classification_uid = 7;
--this is the only aggregate table that includes bike exits
DELETE FROM miovision_api.volumes_daily_unfiltered WHERE
classification_uid = 7 --these we're deleting for good
OR classification_uid = 10; --these we'll need to reaggregate
```
> 1065 miovision stop aggregating bikes in crosswalk

- gis/gccview/gcc_puller_functions.py
- additional error catching for non-200 status code or incorrect return_json fields
- reduce duplication of `query` (only where clause differs)
updated: 
- fixed bug which resulted in 1 too few iterations (max_number incorrectly incremented before 2nd pull)
- reduced some nesting in `get_layer`, `find_limit` functions.
- reran all the affected layers (centreline, centreline_intersection_point, intersection, traffic_bylaw_line/point) from most recent Airflow run and deleted the 20250101 partition where applicable. 
- Added `OBJECTID>0` special case for address point layer which fixed duplicate-key error. 
- Closes #1123, #1124
- Nothing: reran those two failed Sirius layers and they worked (I think the error was transitory, but this will help catch it next time). 
- pull data_scripts on …
> 1123 bug: gcc puller return json keyerror fields

- gis/centreline/sql/create_function_get_centreline_btwn_intersections.sql
- Defines an order for the results returned by the centreline routing function. 
- Orders aggregated results by sequence in the routed path
- Closes #1126
- That this works and nothing breaks. I'm not used to working on SQL within functions.
Since the order was previously undefined, it shouldn't break anything to specify it now.
- replace function with the new definition
> Define order of returned routed centreline links

- .github/workflows/test_dags.yml
- dags/assets_pull.py
- dags/bluetooth_check_readers_temp.py
- dags/check_miovision.py
- dags/check_rescu.py
- dags/citywide_tti_aggregate.py
- dags/dag_functions.py
- dags/ecocounter_pull.py
- dags/eoy_create_tables.py
- dags/gcc_layers_pull.py
- dags/log_cleanup.py
- dags/miovision_pull.py
- dags/pull_here.py
- dags/pull_here_path.py
- dags/pull_interventions_dag.py
- dags/pull_weather.py
- dags/readme.md
- dags/refresh_wys_monthly.py
- dags/replicator_table_check.py
- dags/tti_aggregate.py
- dags/vds_pull_vdsdata.py
- dags/vds_pull_vdsvehicledata.py
- dags/vz_google_sheets.py
- dags/weather_pull.py
- dags/wys_pull.py
- volumes/miovision/api/intersection_tmc.py
- volumes/miovision/api/pull_alert.py
- weather/prediction_import.py
- Removes top level database connections in 3 dags
- schedule_interval -> schedule deprecation warning
- fixes for many other Airflow deprecation warnings
- ~adjust pytest to include warnings~
- I tried upgrading env_canada to latest version to remove a deprecation warning, and then it downgraded google provider to 8.3 (2022). I wasn't comfortable with this so I backtracked on failing on warnings, but the only one remaining is about an env_canada which is about 50 less than before!  
- Closes #1112, #1115
- 
- I checked out this branch in `/data/airflow/data_scripts` to test the many DAG changes, we should revert to master
> #1112 remove top-level connections, fix some import warnings

- volumes/miovision/sql/function/function-aggregate_volumes_daily.sql
- fix ambigous column in function-aggregate_volumes_daily.sql
- tested, working
- #1120
- 
> #1120 fix ambigous column in function-aggregate_volumes_daily.sql

- dags/miovision_pull.py
- dags/wys_pull.py
- fix trigger rules for monthly partition create tasks. 
- Both affected DAGs tested, working ✅ 
- #1141
- 
> #1141 none_failed_min_one_success -> none_failed

- dags/miovision_pull.py
- adds depends_on_past=True to anomalous_range task to prevent edge case where failed tasks are rerun in the wrong order, causing discontinuous ARs
- Tested successfully: 
- Closes #1143
- 
> #1143 depends_on_past=True, remove unused imports

- here/traffic/here_api.py
- fail on non-token related http errors
- fail after max token attempts 
- Closes #1122 
- 
- Update data_scripts
> #1122 HERE: fail on non-token related http errors, fail after max token attempts

- volumes/short_term_counting_program/sql/function-tmc_routine_timebins.sql
- volumes/short_term_counting_program/sql/function-tmc_school_timebins.sql
- 
```sql
--check both functions return 32 time bins:
SELECT array_length(traffic.tmc_school_timebins('2025-01-01'), 1) --32
SELECT array_length(traffic.tmc_routine_timebins('2025-01-01'), 1) --32
```
- #1147
- 
> #1147 create tmc_school_timebins, tmc_routine_timebins functions

- dags/ecocounter_open_data.py
- volumes/open_data/sql/create-view-cycling_permanent_counts_locations_geojson.sql
- Create a view to format open data locations as geojson in postgres
- Add new task to export the view
- #1149 
- 
> 1149 add geojson export to ecocounter open data

- dags/gcc_layers_pull.py
- gis/centreline/readme.md
- gis/centreline/sql/create_matview_centreline_latest.sql
- gis/centreline/sql/create_matview_centreline_latest_all_feature.sql
- gis/centreline/sql/create_trigger_centreline_latest.sql
- gis/gccview/README.md
- gis/gccview/gcc_puller_functions.py
- Add 5 new feature road classes for bigdata ONLY
- new gis_core.centreline_latest_all_feature mat view
- modified gis_core.centreline_latest mat view to include 3 more feature
- #1139
- updated gcc puller function, dag, dag variable, sql for mat view, readme
- create the new centreline latest all feature mat view
- update trigger
- drop all dependency on centreline_latet and recreate......
- git pull data script and update symlink
> Add 5 new feature road classes to centreline

- gis/gccview/gcc_puller_functions.py
- Exclude objectid<=0 from all queries, by recommendation of GCC.
- Note: Of the layers we pull, currently only address_point seems to have negative objectids
- Closes #1138 
- Tested successfully by pulling centreline ✅ 
- Is it the right approach to exclude negative objectid from all layers? I think so.
- Someone from GCC said to
- None of the layers we currently pull have negatives in our database, so effectively no change
> 1138 add note about address point negative objectids

- volumes/miovision/sql/views/create-view-volumes_15min_mvt_filtered.sql
- Adjusts `volumes_15min_mvt_filtered` for null intersection_uid case in anomalous_ranges. Right now we only use this to caution against using data from before 2019 for certain modes. 
- Closes #1172
- 
> #1172 adjust volumes_15min_mvt_filtered for null ar.intersection_uid case

- gis/gccview/gcc_puller_functions.py
- allow null geometries in gcc puller
- #1158 
- I couldn't figure out an arcserver WHERE clause to filter out null geometries, but adding a try..except worked. 
> #1158 allow null geometries in gcc puller

- gis/text_to_centreline/sql/helper_functions/function-abbr_street.sql
Tested: 
```sql
SELECT
val.input,
regexp_REPLACE(val.input, '\(.*\)', '', 'g') AS incorrect,
regexp_REPLACE(val.input, '\(([^\(]+)\)', '', 'g') AS correct
FROM (values('Between Scotswood Road (East Intersection) And Scotswood Road (West Intersection)')) AS val(input)
```
- #1183
- 
> #1183 fix brackets regex in function-abbr_street.sql

- gis/centreline/sql/create_trigger_centreline_latest.sql
- volumes/short_term_counting_program/README.md
- volumes/short_term_counting_program/sql/create-view-svc_centreline_directions.sql
- Creates a view to map SVC count directions like "NB" to actual centreline geometries
- There wasn't a way to do this before
- review continues from https://github.com/Toronto-Big-Data-Innovation-Team/aadt/pull/34
- Create the matview and trigger it to be refreshed whenever `gis_core.centreline_latest` is updated.
> Create view mapping SVC "NB"-type directions to centreline geometries

- volumes/short_term_counting_program/sql/create-view-svc_centreline_directions.sql
- Adds from/to centreline node IDs to the directed SVC view to make it easier to join back to a fuller representation of the centreline network. 
- Would have had to join on a geom field, which seems sketchy
- the code
- recreate the matview (can drop AADT dependents)
> Add from/to "intersection" node IDs to SVC directions view

- dags/gcc_layers_pull.py
- gis/gccview/gcc_puller_functions.py
- gis/gccview/sql/partition_migration/repartition_by_yy_mm_centreline.sql
- gis/gccview/sql/partition_migration/repartition_by_yy_mm_centreline_intersection_point.sql
- gis/gccview/sql/partition_migration/repartition_by_yy_mm_centreline_intersection_point_morbius.sql
- gis/gccview/sql/partition_migration/repartition_by_yy_mm_centreline_morbius.sql
- gis/gccview/sql/partition_migration/repartition_by_yy_mm_intersection.sql
- gis/gccview/sql/partition_migration/repartition_by_yy_mm_intersection_morbius.sql
- change schedule from quarterly to monthly
- adjust puller script to partition first by year (range) then by version_date (list)
- Adjusted to use pendulum instead of datetime which I find a bit more clear
- #1231 
- Just: `gis/gccview/gcc_puller_functions.py`
- the 6 sqls under `partition_migration` folder have already been implemented (tested on personal schema first), so do not need to be reviewed. Committing since they are helpful references for future re-partition exercises.
> GCC - pull layers monthly, repartition

- dags/gcc_layers_pull.py
- gis/gccview/gcc_puller_functions.py
- fix bug in gcc puller row count comparison (wrong date)
- add missing mat view refreshes on morbius/sirius/bancroft
- #1244 
- 
> 1244 gcc puller get dest row count doesnt work for scheduled runs, missing mat view refreshes

- gis/centreline/sql/create_view_intersection_classification.sql
- Add a new column to return sets of centreline_id, road_name, road_class
- #1262 
- that one line
rerun view
> #1262 add roadnameclass column
